### ISSUE TITLE
Add new route properties

### ISSUE THREAD

**Issue by brenoroosevelt** [jerowork/route-attribute-provider#2]
Hi. I'm creating a provider ([here](https://github.com/brenoroosevelt/league-route-attribute-provider/blob/main/src/LeagueRouterAttributeProvider.php)) for [League/Route](https://github.com/thephpleague/route) and I need some extra (optional) properties on the Route attribute:

- Scheme (string);
- Host (string);
- Port (int);
- Strategy (string) - League/Route specific.

These attributes are also found on other routers; except the `strategy`. Is it possible to create these three new properties and also an array for extra fields in the Route attribute? Or some other extension mechanism?

thanks

**Comment by jerowork** [comment]
Hi!

Nice to see you are creating a League implementation.

Good idea to add these extra configuration options, therefore I made a PR: https://github.com/jerowork/route-attribute-provider/pull/3

**Comment by jerowork** [comment]
https://github.com/jerowork/route-attribute-provider#existing-implementations
